python: fix clang infinite-recursion warning
This commit fixes the warning introduced on 15d7074f55a2c3dd38ce9877626be6ec32b448d2

Thanks to clang compiler the following warning discovered:
../../../../../../lib/python/python.h:41:26: error: all paths through this function will call itself [-Werror,-Winfinite-recursion]
        operator PyVarObject*() { return (PyVarObject*)operator PyVarObject*(); }
                                ^

We should use the PyObject just like we do on other operators.