gpixmap: fix convertion of gRGB tostring on clang
When using clang the gRGB fails to convert into string with the following message:
gui/esubtitle.cpp:400:28: error: no viable conversion from 'gRGB' to 'std::__cxx11::basic_string<char>'
                                                text = (std::string) gRGB(255, 255, 0) + text;
                                                                     ^~~~~~~~~~~~~~~~~