[FrontendInfo.py] Fixed 12+ year old bug in tuner "TYPE"
This was broken (instant crash if a skin asks for tuner "TYPE") since its introduction, back in 2007 https://github.com/OpenPLi/enigma2/commit/f5f70f0586875cf34ab93c7abd1cf7165badf399#diff-ea48bab53642d137a22c2c760fd1200c

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Navigation.py", line 69, in dispatchEvent
  File "/usr/lib/enigma2/python/Components/PerServiceDisplay.py", line 19, in event
  File "/usr/lib/enigma2/python/Components/Sources/FrontendInfo.py", line 37, in updateFrontendData
  File "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
  File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
  File "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
  File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
  File "/usr/lib/enigma2/python/Components/Renderer/Label.py", line 24, in changed
  File "/usr/lib/enigma2/python/Components/Element.py", line 15, in wrapper
  File "/usr/lib/enigma2/python/Components/Converter/FrontendInfo.py", line 66, in getText
AttributeError: 'FrontendInfo' object has no attribute 'frontend_type'
[ePyObject] (CallObject(<bound method Navigation.dispatchEvent of <Navigation.Navigation instance at 0x7f8cab0a28>>,(2,)
) failed)